//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_FLOATRANGESLOWRANGEQUERY_HPP
#define LUCENECPP20_FLOATRANGESLOWRANGEQUERY_HPP


class FloatRangeSlowRangeQuery {

};


#endif //LUCENECPP20_FLOATRANGESLOWRANGEQUERY_HPP
