//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_FLOATRANGEDOCVALUESFIELD_HPP
#define LUCENECPP20_FLOATRANGEDOCVALUESFIELD_HPP


class FloatRangeDocValuesField {

};


#endif //LUCENECPP20_FLOATRANGEDOCVALUESFIELD_HPP
