//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_INTRANGEDOCVALUESFIELD_HPP
#define LUCENECPP20_INTRANGEDOCVALUESFIELD_HPP


class IntRangeDocValuesField {

};


#endif //LUCENECPP20_INTRANGEDOCVALUESFIELD_HPP
