//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_LATLONDOCVALUESQUERY_HPP
#define LUCENECPP20_LATLONDOCVALUESQUERY_HPP


class LatLonDocValuesQuery {

};


#endif //LUCENECPP20_LATLONDOCVALUESQUERY_HPP
