//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_LATLONPOINTDISTANCEFEATUREQUERY_HPP
#define LUCENECPP20_LATLONPOINTDISTANCEFEATUREQUERY_HPP


class LatLonPointDistanceFeatureQuery {

};


#endif //LUCENECPP20_LATLONPOINTDISTANCEFEATUREQUERY_HPP
