//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_LATLONSHAPEBOUNDINGBOXQUERY_HPP
#define LUCENECPP20_LATLONSHAPEBOUNDINGBOXQUERY_HPP


class LatLonShapeBoundingBoxQuery {

};


#endif //LUCENECPP20_LATLONSHAPEBOUNDINGBOXQUERY_HPP
