//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_LATLONPOINTDISTANCECOMPARATOR_HPP
#define LUCENECPP20_LATLONPOINTDISTANCECOMPARATOR_HPP


class LatLonPointDistanceComparator {

};


#endif //LUCENECPP20_LATLONPOINTDISTANCECOMPARATOR_HPP
