//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_NUMERICDOCVALUESFIELD_HPP
#define LUCENECPP20_NUMERICDOCVALUESFIELD_HPP


class NumericDocValuesField {

};


#endif //LUCENECPP20_NUMERICDOCVALUESFIELD_HPP
