//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_SORTEDSETDOCVALUESRANGEQUERY_HPP
#define LUCENECPP20_SORTEDSETDOCVALUESRANGEQUERY_HPP


class SortedSetDocValuesRangeQuery {

};


#endif //LUCENECPP20_SORTEDSETDOCVALUESRANGEQUERY_HPP
