//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_SORTEDNUMERICDOCVALUESFIELD_HPP
#define LUCENECPP20_SORTEDNUMERICDOCVALUESFIELD_HPP


class SortedNumericDocValuesField {

};


#endif //LUCENECPP20_SORTEDNUMERICDOCVALUESFIELD_HPP
