//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_SORTEDNUMERICDOCVALUESRANGEQUERY_HPP
#define LUCENECPP20_SORTEDNUMERICDOCVALUESRANGEQUERY_HPP


class SortedNumericDocValuesRangeQuery {

};


#endif //LUCENECPP20_SORTEDNUMERICDOCVALUESRANGEQUERY_HPP
