//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_SORTEDSETDOCVALUESFIELD_HPP
#define LUCENECPP20_SORTEDSETDOCVALUESFIELD_HPP


class SortedSetDocValuesField {

};


#endif //LUCENECPP20_SORTEDSETDOCVALUESFIELD_HPP
