//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_XYDOCVALUESPOINTINGEOMETRYQUERY_HPP
#define LUCENECPP20_XYDOCVALUESPOINTINGEOMETRYQUERY_HPP


class XYDocValuesPointInGeometryQuery {

};


#endif //LUCENECPP20_XYDOCVALUESPOINTINGEOMETRYQUERY_HPP
