//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_XYPOINTSORTFIELD_HPP
#define LUCENECPP20_XYPOINTSORTFIELD_HPP


class XYPointSortField {

};


#endif //LUCENECPP20_XYPOINTSORTFIELD_HPP
