//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_XYPOINTDISTANCECOMPARATOR_HPP
#define LUCENECPP20_XYPOINTDISTANCECOMPARATOR_HPP


class XYPointDistanceComparator {

};


#endif //LUCENECPP20_XYPOINTDISTANCECOMPARATOR_HPP
