//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_AUTOMATONTERMSENUM_HPP
#define LUCENECPP20_AUTOMATONTERMSENUM_HPP


class AutomatonTermsEnum {

};


#endif //LUCENECPP20_AUTOMATONTERMSENUM_HPP
