//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_BINARYDOCVALUESFIELDUPDATES_HPP
#define LUCENECPP20_BINARYDOCVALUESFIELDUPDATES_HPP


class BinaryDocValuesFieldUpdates {

};


#endif //LUCENECPP20_BINARYDOCVALUESFIELDUPDATES_HPP
