//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_BUFFEREDUPDATESSTREAM_HPP
#define LUCENECPP20_BUFFEREDUPDATESSTREAM_HPP


class BufferedUpdatesStream {

};


#endif //LUCENECPP20_BUFFEREDUPDATESSTREAM_HPP
