//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_COMPOSITEREADERCONTEXT_HPP
#define LUCENECPP20_COMPOSITEREADERCONTEXT_HPP


class CompositeReaderContext {

};


#endif //LUCENECPP20_COMPOSITEREADERCONTEXT_HPP
