//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_CORRUPTINDEXEXCEPTION_HPP
#define LUCENECPP20_CORRUPTINDEXEXCEPTION_HPP


class CorruptIndexException {

};


#endif //LUCENECPP20_CORRUPTINDEXEXCEPTION_HPP
