//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_DOCUMENTSWRITERFLUSHCONTROL_HPP
#define LUCENECPP20_DOCUMENTSWRITERFLUSHCONTROL_HPP


class DocumentsWriterFlushControl {

};


#endif //LUCENECPP20_DOCUMENTSWRITERFLUSHCONTROL_HPP
