//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_DOCUMENTSWRITERPERTHREADPOOL_HPP
#define LUCENECPP20_DOCUMENTSWRITERPERTHREADPOOL_HPP


class DocumentsWriterPerThreadPool {

};


#endif //LUCENECPP20_DOCUMENTSWRITERPERTHREADPOOL_HPP
