//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_DOCUMENTSWRITERDELETEQUEUE_HPP
#define LUCENECPP20_DOCUMENTSWRITERDELETEQUEUE_HPP


class DocumentsWriterDeleteQueue {

};


#endif //LUCENECPP20_DOCUMENTSWRITERDELETEQUEUE_HPP
