//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_DOCUMENTSWRITERSTALLCONTROL_HPP
#define LUCENECPP20_DOCUMENTSWRITERSTALLCONTROL_HPP


class DocumentsWriterStallControl {

};


#endif //LUCENECPP20_DOCUMENTSWRITERSTALLCONTROL_HPP
