//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_DOCVALUESLEAFREADER_HPP
#define LUCENECPP20_DOCVALUESLEAFREADER_HPP


class DocValuesLeafReader {

};


#endif //LUCENECPP20_DOCVALUESLEAFREADER_HPP
