//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_DOCVALUESFIELDUPDATES_HPP
#define LUCENECPP20_DOCVALUESFIELDUPDATES_HPP


class DocValuesFieldUpdates {

};


#endif //LUCENECPP20_DOCVALUESFIELDUPDATES_HPP
