//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_EXITABLEDIRECTORYREADER_HPP
#define LUCENECPP20_EXITABLEDIRECTORYREADER_HPP


class ExitableDirectoryReader {

};


#endif //LUCENECPP20_EXITABLEDIRECTORYREADER_HPP
