//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_FILTERNUMERICDOCVALUES_HPP
#define LUCENECPP20_FILTERNUMERICDOCVALUES_HPP


class FilterNumericDocValues {

};


#endif //LUCENECPP20_FILTERNUMERICDOCVALUES_HPP
