//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_FILTERSORTEDSETDOCVALUES_HPP
#define LUCENECPP20_FILTERSORTEDSETDOCVALUES_HPP


class FilterSortedSetDocValues {

};


#endif //LUCENECPP20_FILTERSORTEDSETDOCVALUES_HPP
