//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_FILTERSORTEDDOCVALUES_HPP
#define LUCENECPP20_FILTERSORTEDDOCVALUES_HPP


class FilterSortedDocValues {

};


#endif //LUCENECPP20_FILTERSORTEDDOCVALUES_HPP
