//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_FILTERBINARYDOCVALUES_HPP
#define LUCENECPP20_FILTERBINARYDOCVALUES_HPP


class FilterBinaryDocValues {

};


#endif //LUCENECPP20_FILTERBINARYDOCVALUES_HPP
