//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_FILTERSORTEDNUMERICDOCVALUES_HPP
#define LUCENECPP20_FILTERSORTEDNUMERICDOCVALUES_HPP


class FilterSortedNumericDocValues {

};


#endif //LUCENECPP20_FILTERSORTEDNUMERICDOCVALUES_HPP
