//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_FLUSHBYRAMORCOUNTSPOLICY_HPP
#define LUCENECPP20_FLUSHBYRAMORCOUNTSPOLICY_HPP


class FlushByRamOrCountsPolicy {

};


#endif //LUCENECPP20_FLUSHBYRAMORCOUNTSPOLICY_HPP
