//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_FREQPROXTERMSWRITERPERFIELD_HPP
#define LUCENECPP20_FREQPROXTERMSWRITERPERFIELD_HPP


class FreqProxTermsWriterPerField {

};


#endif //LUCENECPP20_FREQPROXTERMSWRITERPERFIELD_HPP
