//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_FROZENBUFFEREDUPDATES_HPP
#define LUCENECPP20_FROZENBUFFEREDUPDATES_HPP


class FrozenBufferedUpdates {

};


#endif //LUCENECPP20_FROZENBUFFEREDUPDATES_HPP
