//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_INDEXNOTFOUNDEXCEPTION_HPP
#define LUCENECPP20_INDEXNOTFOUNDEXCEPTION_HPP


class IndexNotFoundException {

};


#endif //LUCENECPP20_INDEXNOTFOUNDEXCEPTION_HPP
