//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_INDEXDELETIONPOLICY_HPP
#define LUCENECPP20_INDEXDELETIONPOLICY_HPP


class IndexDeletionPolicy {

};


#endif //LUCENECPP20_INDEXDELETIONPOLICY_HPP
