//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_INDEXFORMATTOOOLDEXCEPTION_HPP
#define LUCENECPP20_INDEXFORMATTOOOLDEXCEPTION_HPP


class IndexFormatTooOldException {

};


#endif //LUCENECPP20_INDEXFORMATTOOOLDEXCEPTION_HPP
