//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_KEEPONLYLASTCOMMITDELETIONPOLICY_HPP
#define LUCENECPP20_KEEPONLYLASTCOMMITDELETIONPOLICY_HPP


class KeepOnlyLastCommitDeletionPolicy {

};


#endif //LUCENECPP20_KEEPONLYLASTCOMMITDELETIONPOLICY_HPP
