//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_LIVEINDEXWRITERCONFIG_HPP
#define LUCENECPP20_LIVEINDEXWRITERCONFIG_HPP


class LiveIndexWriterConfig {

};


#endif //LUCENECPP20_LIVEINDEXWRITERCONFIG_HPP
