//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_LOGDOCMERGEPOLICY_HPP
#define LUCENECPP20_LOGDOCMERGEPOLICY_HPP


class LogDocMergePolicy {

};


#endif //LUCENECPP20_LOGDOCMERGEPOLICY_HPP
