//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_MAPPINGMULTIPOSTINGSENUM_HPP
#define LUCENECPP20_MAPPINGMULTIPOSTINGSENUM_HPP


class MappingMultiPostingsEnum {

};


#endif //LUCENECPP20_MAPPINGMULTIPOSTINGSENUM_HPP
