//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_NUMERICDOCVALUESFIELDUPDATES_HPP
#define LUCENECPP20_NUMERICDOCVALUESFIELDUPDATES_HPP


class NumericDocValuesFieldUpdates {

};


#endif //LUCENECPP20_NUMERICDOCVALUESFIELDUPDATES_HPP
