//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_NUMERICDOCVALUESWRITER_HPP
#define LUCENECPP20_NUMERICDOCVALUESWRITER_HPP


class NumericDocValuesWriter {

};


#endif //LUCENECPP20_NUMERICDOCVALUESWRITER_HPP
