//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_ONEMERGEWRAPPINGMERGEPOLICY_HPP
#define LUCENECPP20_ONEMERGEWRAPPINGMERGEPOLICY_HPP


class OneMergeWrappingMergePolicy {

};


#endif //LUCENECPP20_ONEMERGEWRAPPINGMERGEPOLICY_HPP
