//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_PARALLELCOMPOSITEREADER_HPP
#define LUCENECPP20_PARALLELCOMPOSITEREADER_HPP


class ParallelCompositeReader {

};


#endif //LUCENECPP20_PARALLELCOMPOSITEREADER_HPP
