//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_PERSISTENTSNAPSHOTDELETIONPOLICY_HPP
#define LUCENECPP20_PERSISTENTSNAPSHOTDELETIONPOLICY_HPP


class PersistentSnapshotDeletionPolicy {

};


#endif //LUCENECPP20_PERSISTENTSNAPSHOTDELETIONPOLICY_HPP
