//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_RANDOMACCESSVECTORVALUESPRODUCER_HPP
#define LUCENECPP20_RANDOMACCESSVECTORVALUESPRODUCER_HPP


class RandomAccessVectorValuesProducer {

};


#endif //LUCENECPP20_RANDOMACCESSVECTORVALUESPRODUCER_HPP
