//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_RANDOMACCESSVECTORVALUES_HPP
#define LUCENECPP20_RANDOMACCESSVECTORVALUES_HPP


class RandomAccessVectorValues {

};


#endif //LUCENECPP20_RANDOMACCESSVECTORVALUES_HPP
