//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_SEGMENTCOREREADERS_HPP
#define LUCENECPP20_SEGMENTCOREREADERS_HPP


class SegmentCoreReaders {

};


#endif //LUCENECPP20_SEGMENTCOREREADERS_HPP
