//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_SEGMENTDOCVALUESPRODUCER_HPP
#define LUCENECPP20_SEGMENTDOCVALUESPRODUCER_HPP


class SegmentDocValuesProducer {

};


#endif //LUCENECPP20_SEGMENTDOCVALUESPRODUCER_HPP
