//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_SERIALMERGESCHEDULER_HPP
#define LUCENECPP20_SERIALMERGESCHEDULER_HPP


class SerialMergeScheduler {

};


#endif //LUCENECPP20_SERIALMERGESCHEDULER_HPP
