//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_SIMPLEMERGEDSEGMENTWARMER_HPP
#define LUCENECPP20_SIMPLEMERGEDSEGMENTWARMER_HPP


class SimpleMergedSegmentWarmer {

};


#endif //LUCENECPP20_SIMPLEMERGEDSEGMENTWARMER_HPP
