//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_SINGLETONSORTEDSETDOCVALUES_HPP
#define LUCENECPP20_SINGLETONSORTEDSETDOCVALUES_HPP


class SingletonSortedSetDocValues {

};


#endif //LUCENECPP20_SINGLETONSORTEDSETDOCVALUES_HPP
