//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_SINGLETONSORTEDNUMERICDOCVALUES_HPP
#define LUCENECPP20_SINGLETONSORTEDNUMERICDOCVALUES_HPP


class SingletonSortedNumericDocValues {

};


#endif //LUCENECPP20_SINGLETONSORTEDNUMERICDOCVALUES_HPP
