//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_SNAPSHOTDELETIONPOLICY_HPP
#define LUCENECPP20_SNAPSHOTDELETIONPOLICY_HPP


class SnapshotDeletionPolicy {

};


#endif //LUCENECPP20_SNAPSHOTDELETIONPOLICY_HPP
