//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_SOFTDELETESDIRECTORYREADERWRAPPER_HPP
#define LUCENECPP20_SOFTDELETESDIRECTORYREADERWRAPPER_HPP


class SoftDeletesDirectoryReaderWrapper {

};


#endif //LUCENECPP20_SOFTDELETESDIRECTORYREADERWRAPPER_HPP
