//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_SOFTDELETESRETENTIONMERGEPOLICY_HPP
#define LUCENECPP20_SOFTDELETESRETENTIONMERGEPOLICY_HPP


class SoftDeletesRetentionMergePolicy {

};


#endif //LUCENECPP20_SOFTDELETESRETENTIONMERGEPOLICY_HPP
