//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_SORTINGSTOREDFIELDSCONSUMER_HPP
#define LUCENECPP20_SORTINGSTOREDFIELDSCONSUMER_HPP


class SortingStoredFieldsConsumer {

};


#endif //LUCENECPP20_SORTINGSTOREDFIELDSCONSUMER_HPP
