//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_SORTEDNUMERICDOCVALUESWRITER_HPP
#define LUCENECPP20_SORTEDNUMERICDOCVALUESWRITER_HPP


class SortedNumericDocValuesWriter {

};


#endif //LUCENECPP20_SORTEDNUMERICDOCVALUESWRITER_HPP
