//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_SORTINGCODECREADER_HPP
#define LUCENECPP20_SORTINGCODECREADER_HPP


class SortingCodecReader {

};


#endif //LUCENECPP20_SORTINGCODECREADER_HPP
