//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_SORTEDDOCVALUESWRITER_HPP
#define LUCENECPP20_SORTEDDOCVALUESWRITER_HPP


class SortedDocValuesWriter {

};


#endif //LUCENECPP20_SORTEDDOCVALUESWRITER_HPP
