//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_SORTEDSETDOCVALUESTERMSENUM_HPP
#define LUCENECPP20_SORTEDSETDOCVALUESTERMSENUM_HPP


class SortedSetDocValuesTermsEnum {

};


#endif //LUCENECPP20_SORTEDSETDOCVALUESTERMSENUM_HPP
