//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_SORTEDSETDOCVALUES_HPP
#define LUCENECPP20_SORTEDSETDOCVALUES_HPP


class SortedSetDocValues {

};


#endif //LUCENECPP20_SORTEDSETDOCVALUES_HPP
