//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_SORTEDDOCVALUESTERMSENUM_HPP
#define LUCENECPP20_SORTEDDOCVALUESTERMSENUM_HPP


class SortedDocValuesTermsEnum {

};


#endif //LUCENECPP20_SORTEDDOCVALUESTERMSENUM_HPP
