//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_SORTEDSETDOCVALUESWRITER_HPP
#define LUCENECPP20_SORTEDSETDOCVALUESWRITER_HPP


class SortedSetDocValuesWriter {

};


#endif //LUCENECPP20_SORTEDSETDOCVALUESWRITER_HPP
