//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_SORTEDNUMERICDOCVALUES_HPP
#define LUCENECPP20_SORTEDNUMERICDOCVALUES_HPP


class SortedNumericDocValues {

};


#endif //LUCENECPP20_SORTEDNUMERICDOCVALUES_HPP
