//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_STOREDFIELDSCONSUMER_HPP
#define LUCENECPP20_STOREDFIELDSCONSUMER_HPP


class StoredFieldsConsumer {

};


#endif //LUCENECPP20_STOREDFIELDSCONSUMER_HPP
