//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_STOREDFIELDVISITOR_HPP
#define LUCENECPP20_STOREDFIELDVISITOR_HPP


class StoredFieldVisitor {

};


#endif //LUCENECPP20_STOREDFIELDVISITOR_HPP
