//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_TERMVECTORSCONSUMER_HPP
#define LUCENECPP20_TERMVECTORSCONSUMER_HPP


class TermVectorsConsumer {

};


#endif //LUCENECPP20_TERMVECTORSCONSUMER_HPP
