//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_TERMSHASHPERFIELD_HPP
#define LUCENECPP20_TERMSHASHPERFIELD_HPP


class TermsHashPerField {

};


#endif //LUCENECPP20_TERMSHASHPERFIELD_HPP
