//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_TERMVECTORSCONSUMERPERFIELD_HPP
#define LUCENECPP20_TERMVECTORSCONSUMERPERFIELD_HPP


class TermVectorsConsumerPerField {

};


#endif //LUCENECPP20_TERMVECTORSCONSUMERPERFIELD_HPP
