//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_TRACKINGTMPOUTPUTDIRECTORYWRAPPER_HPP
#define LUCENECPP20_TRACKINGTMPOUTPUTDIRECTORYWRAPPER_HPP


class TrackingTmpOutputDirectoryWrapper {

};


#endif //LUCENECPP20_TRACKINGTMPOUTPUTDIRECTORYWRAPPER_HPP
