//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_TWOPHASECOMMITTOOL_HPP
#define LUCENECPP20_TWOPHASECOMMITTOOL_HPP


class TwoPhaseCommitTool {

};


#endif //LUCENECPP20_TWOPHASECOMMITTOOL_HPP
