//
// Created by Ervin Bosenbacher on 17/06/2021.
//

#ifndef LUCENECPP20_VECTORVALUESWRITER_HPP
#define LUCENECPP20_VECTORVALUESWRITER_HPP


class VectorValuesWriter {

};


#endif //LUCENECPP20_VECTORVALUESWRITER_HPP
